# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Process_Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('preprocesses', models.ManyToManyField(related_name='_process_blueprint_preprocesses_+', to='Process.Process_Blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Real', 'Real'), ('Document', 'Document'), ('Multiple Choice', 'Multiple Choice')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Task',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Task')),
                ('answer_set', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Answer_Set')),
            ],
            bases=('Process.task',),
        ),
        migrations.CreateModel(
            name='Employee_Task_Blueprint',
            fields=[
                ('task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Task_Blueprint')),
                ('question_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Question_Set')),
            ],
            bases=('Process.task_blueprint',),
        ),
        migrations.CreateModel(
            name='Student_Task',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Task')),
                ('start_time', models.DateTimeField(default=datetime.timedelta(0))),
            ],
            bases=('Process.task',),
        ),
        migrations.CreateModel(
            name='Student_Task_Blueprint',
            fields=[
                ('task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Task_Blueprint')),
                ('is_timed', models.BooleanField(default=False)),
                ('max_time', models.DateTimeField(default=datetime.timedelta(0))),
            ],
            bases=('Process.task_blueprint',),
        ),
        migrations.AddField(
            model_name='task_blueprint',
            name='default_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.Process_Blueprint'),
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Process'),
        ),
        migrations.AddField(
            model_name='question',
            name='belongs_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Process.Question_Set'),
        ),
        migrations.AddField(
            model_name='process',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Process_Blueprint'),
        ),
        migrations.AddField(
            model_name='process',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='belongs_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Process.Answer_Set'),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('student_task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Student_Task')),
                ('answer_set', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Answer_Set')),
            ],
            bases=('Process.student_task',),
        ),
        migrations.CreateModel(
            name='Form_Blueprint',
            fields=[
                ('student_task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Student_Task_Blueprint')),
                ('question_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Question_Set')),
            ],
            bases=('Process.student_task_blueprint',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('student_task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Student_Task')),
                ('paid', models.IntegerField(default=0)),
            ],
            bases=('Process.student_task',),
        ),
        migrations.CreateModel(
            name='Payment_Blueprint',
            fields=[
                ('student_task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Process.Student_Task_Blueprint')),
                ('receiver', models.IntegerField(default=0)),
                ('default_amount', models.IntegerField(null=True)),
            ],
            bases=('Process.student_task_blueprint',),
        ),
        migrations.AddField(
            model_name='employee_task',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Employee_Task_Blueprint'),
        ),
        migrations.AddField(
            model_name='payment',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Payment_Blueprint'),
        ),
        migrations.AddField(
            model_name='form',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.Form_Blueprint'),
        ),
    ]
