# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.Department'),
        ),
    ]
