# Generated by Django 2.0.2 on 2018-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='alaki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
    ]
