# Generated by Django 2.0.2 on 2018-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0003_alaki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alaki',
            name='question_text',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
