# Generated by Django 2.0.2 on 2018-02-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0004_auto_20180202_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alaki',
        ),
    ]
