# Generated by Django 2.0.2 on 2018-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0005_delete_alaki'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task',
            name='textsss',
            field=models.CharField(default='text', max_length=200),
            preserve_default=False,
        ),
    ]
