# Generated by Django 2.0.2 on 2018-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0007_auto_20180202_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.IntegerField(default=0),
        ),
    ]
