# Generated by Django 2.0.2 on 2018-02-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0008_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_task',
            name='textsss',
        ),
        migrations.AddField(
            model_name='process',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
