# Generated by Django 2.0.2 on 2018-02-02 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0009_auto_20180202_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 10, 18, 5, 617243, tzinfo=utc)),
        ),
    ]
