# Generated by Django 2.0.2 on 2018-02-02 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0010_student_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_task',
            name='start_time',
            field=models.DateTimeField(default=datetime.timedelta(0)),
        ),
    ]
