# Generated by Django 2.0.2 on 2018-02-02 16:36

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0011_auto_20180202_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('student_task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.Student_Task')),
                ('answer_set', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Answer_Set')),
            ],
            bases=('graduate.student_task',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('student_task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.Student_Task')),
                ('amount', models.IntegerField(default=0)),
            ],
            bases=('graduate.student_task',),
        ),
        migrations.CreateModel(
            name='Process_Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('preprocesses', models.ManyToManyField(related_name='_process_blueprint_preprocesses_+', to='graduate.Process_Blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('question_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Real', 'Real'), ('Document', 'Document'), ('Multiple Choice', 'Multiple Choice')], max_length=20), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.IntegerField(default=0)),
                ('logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='employee_task',
            name='age',
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Process'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.User')),
                ('employee_id', models.IntegerField(default=0)),
                ('ready', models.BooleanField(default=True)),
                ('operator_authority', models.BooleanField(default=False)),
                ('works_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graduate.Department')),
            ],
            bases=('graduate.user',),
        ),
        migrations.CreateModel(
            name='Employee_Task_Blueprint',
            fields=[
                ('task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.Task_Blueprint')),
                ('question_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Question_Set')),
            ],
            bases=('graduate.task_blueprint',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.User')),
                ('student_id', models.IntegerField(default=0)),
                ('graduated', models.BooleanField(default=False)),
            ],
            bases=('graduate.user',),
        ),
        migrations.CreateModel(
            name='Student_Task_Blueprint',
            fields=[
                ('task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.Task_Blueprint')),
                ('is_timed', models.BooleanField(default=False)),
                ('max_time', models.DateTimeField(default=datetime.timedelta(0))),
            ],
            bases=('graduate.task_blueprint',),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='task_blueprint',
            name='default_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduate.Process_Blueprint'),
        ),
        migrations.AddField(
            model_name='employee_task',
            name='answer_set',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Answer_Set'),
        ),
        migrations.AddField(
            model_name='process',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Process_Blueprint'),
        ),
        migrations.CreateModel(
            name='Form_Blueprint',
            fields=[
                ('student_task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.Student_Task_Blueprint')),
                ('question_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Question_Set')),
            ],
            bases=('graduate.student_task_blueprint',),
        ),
        migrations.CreateModel(
            name='Payment_Blueprint',
            fields=[
                ('student_task_blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduate.Student_Task_Blueprint')),
                ('receiver', models.IntegerField(default=0)),
            ],
            bases=('graduate.student_task_blueprint',),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graduate.Employee'),
        ),
        migrations.AddField(
            model_name='employee_task',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Employee_Task_Blueprint'),
        ),
        migrations.AddField(
            model_name='process',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Payment_Blueprint'),
        ),
        migrations.AddField(
            model_name='form',
            name='instance_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Form_Blueprint'),
        ),
    ]
