# Generated by Django 2.0.2 on 2018-02-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0012_auto_20180202_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Real', 'Real'), ('Document', 'Document'), ('Multiple Choice', 'Multiple Choice')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer_set',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question_set',
            name='question_types',
        ),
        migrations.RemoveField(
            model_name='question_set',
            name='questions',
        ),
        migrations.AddField(
            model_name='answer_set',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='question_set',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Question_Set'),
        ),
        migrations.AddField(
            model_name='answer',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduate.Answer_Set'),
        ),
    ]
