# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MyUser.BaseUser')),
                ('student_id', models.IntegerField()),
                ('graduated', models.BooleanField(default=False)),
                ('major', models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=20)),
            ],
            bases=('MyUser.baseuser',),
        ),
    ]
